# Definitions the name of Workflow.
name: Test Azure Login With OpenID Connect with Service Principal.

on: [push] # Got trigger when push request to the repository.

permissions:
  id-token: write # write down id_token when login to Azure.
  contents: read # read specified branch of the repository.

jobs:

  # job : show azure account information.
  build_azure_resources:

    # execute this job on ubuntu-latest environment.
    runs-on: ubuntu-latest

    steps:

    # step 1. Login to Azure with Service Principal.
    - name: Login to Azure with Service Principal.
      uses: azure/login@v1 # Github actions for Azure login.

      # the parameters for the action.
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    # step 2. Show account information.
    - name: Show account information.

      # execute the command to show account information.
      run: |
        az account show
